server:
  port: 9000

logging:
  level:
    root: warn
    me.sonam.auth: info
    org.springframework.web: error
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: update