server:
  port: ${AUTH_SERVER_PORT}
  servlet:
    context-path: /issuer

logging:
  level:
    root: warn
    me.sonam.auth: info
    com.netflix: off
    me.sonam.auth.config: debug
#    org.springframework.web: info
#    org.springframework.security: info
#    org.springframework.security.oauth2: info
#    org.springframework.boot.autoconfigure: warn

spring:
  profiles:
    active: local
  application:
    name: authorization-server
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  thymeleaf: # to enable hot reload of Thymeleaf templates
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

application-rest-service:
  root: ${APPLICATION_REST_SERVICE}
  client-role: /applications/clients/{clientId}/users/{authenticationId}

authentication-rest-service:
  root: ${AUTHENTICATION_REST_SERVICE}
  authenticate: /authentications/authenticate

user-rest-service:
  root: ${USER_REST_SERVICE}
  context: /users
  userByAuthId: ${user-rest-service.context}/{authenticationId}

organization-rest-service:
  root: ${ORGANIZATION_REST_SERVICE}
  userExistsInOrganization: /organizations/{organizationId}/users/{userId}

account-rest-service:
  root: ${ACCOUNT_REST_SERVICE}
  context: /accounts
  emailUsername: /email/{email}/authentication-id
  emailMySecret: /email/{email}/password-secret
  emailActivateLink: /active/email/{email}/password-secret
  validateEmailLoginSecret: /{email}/password-secret/{secret}
  updatePassword: /password-secret

oauth2-token-mediator:
  root: ${TOKEN_MEDIATOR}
  clients: /oauth2-token-mediator/clients

# this is used for getting accesstoken by header filter
auth-server:
  root: http://authorization-server/issuer
  oauth2token:
    path: /oauth2/token
    grantType: client_credentials

client:
  url: ${client-app}
  forgot-username-password: /forgot

jwtrequest:
  - in: /*
    out: /users,/users/(.)*
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}
  - in: /*
    out: /organizations/(.)*/users/(.)*
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}
  - in: /*
    out: /oauth2-token-mediator/clients
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}
  - in: /*
    out: /oauth2-token-mediator/clients/(.)*
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}
  - in: /*
    out: /accounts/active/email-link/(.)*, /accounts/email/(.)*, 
          /accounts/email/(.)*/authenticationId, /accounts/active/email/(.)*/password-secret,
          /accounts/(.)*/password-secret/(.)*, /accounts/password-secret
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}
