# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
AUTH_SERVER_PORT: 9001

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: authorization
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test
EUREKA_CLIENT_ENABLED: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

APPLICATION_REST_SERVICE: http://application-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service
USER_REST_SERVICE: http://user-rest-service
ORGANIZATION_REST_SERVICE: http://organization-rest-service
ACCOUNT_REST_SERVICE: http://account-rest-service
TOKEN_MEDIATOR: http://oauth2-token-mediator
API_GATEWAY: http://api-gateway:8080

# ISSUER_URL here is used for pulling the public certs from authorization-server for token validation
ISSUER_ADDRESS: http://api-gateway:9001
ISSUER_URI: ${ISSUER_ADDRESS}/issuer


REQUEST_SCOPES: message.read message.write
BASE64_CLIENT_ID_SECRET: b2F1dGgtY2xpZW50Om9hdXRoLXNlY3JldA==

client-app: http://10.0.0.28:3000
changePassword: /issuer/forgot/changePassword #@{/forgot/changePassword} use for local
allowedOrigins: http://api-gateway, 10.0.0.28, localhost, 127.0.0.1, api-gateway, 10.0.0.28:8080, 127.0.0.1

NEW_RELIC_ENABLED: false
authzmanager: http://localhost:9093