# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
AUTH_SERVER_PORT: 9001

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: authorization
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test
EUREKA_CLIENT_ENABLED: true

DEFAULT_ZONE: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka
APPLICATION_REST_SERVICE: http://application-rest-service
AUTHENTICATION_REST_SERVICE: http://authentication-rest-service
USER_REST_SERVICE: http://user-rest-service
TOKEN_MEDIATOR: http://oauth2-token-mediator

# ISSUER_URL here is used for pulling the public certs from authorization-server for token validation
#ISSUER_URL:  http://10.0.0.28:9001
#ISSUER_URL: http://authorization-server:9001
#ISSUER_URL: http://127.0.0.1:9001  this works
#ISSUER_URL: http://my-server:9001
ISSUER_URL: http://api-gateway:9001/issuer #trying this instead of http://my-server:9001

private-client-url: http://127.0.0.1:8090