# this profile is activated by kubernetes dependencies
spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        namespaces:
           - backend
        include-not-ready-addresses: true
eureka:
  client:
      enabled: false

allowedOrigins: ${ALLOWED_ORIGINS}  #localhost
authzmanager: https://authzmanager.sonam.cloud