apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-service-client-credential-flow-secret
  namespace: backend
spec:
  encryptedData:
    base64EncodedClientIdSecret: AgAi7igQQCbM8sfTpsRLnjm7p6p7irCazehVDTTpKfAgSh6wdPE24QXuBeaE9asRhgJ/b0io8yDMdnhBOiCpKLPOj9KhwlveCiB1V0vr0ekRI3qRphgIw+XnC2J4oA7Rmszd7fC9gen0ctkpJE19H7cIf+HuprSUG6QFU8IsgWXXhmMRuAwjbxlEsrThimEMyfxdreVCJt51cgCnitxEXz0+hVydiueAE44GIB0B8pL3KPBMZ1ROLGPCAUYOcXrckLIdCiVV/CXOZIEswztmQHPljfP+lsqhAZaSTiNULVsKrJ1zUii/lhjlwphvlnT7Tct7sbYBSnCyeo+nAYVMhT5zJdZvu/+ZNqk/FEvTH+n3iIDHhHS3FzQmi1fAj/3BD3uzxECIsv95Zw/QM+1/KgmWGKBJSdgJbY1lzyW+XLPXdnjZQ1k5vB7DqZbMIoMuomdXust9WuM8Le2hH7C08Z8vtuakXvPUc3wYl89OSe8sP4rQCFuVNu1R1N5AzcPmFz9A1kIa6WjKT4EGWiqMtMxae/lU+JYcSDzrPSQ0Bn0uiTcudpnssymwL39/fW670uFSJnlD/b4JkilghX7Ob6oZ6NhbX+oGYG0DlvPnhQbLf/buXd6SjRL9OtI/ForAWKVlm83JY9hPc38ES6W0CmGtpZlyMT886fnnX4K3w3r68yhYohRiW6y0pAi+UBeb3/CP8wZfaNHmnja4KGrL4Su8I3RIxXHBMt7GiTaeFB7mCokV0TI=
    scopes: AgAdSrFDCRZwqiKy+UQO3CBvQVDXXdnKFhJfno7M+xciwvuJuXRTIvqqu63+YpJO50Rf6E0SCbTAREAUJbr05ot8vAT2v9bvX4ZAxVKjMv7It9Irq8kCFZyprO5vEbVo9iPU44cO+532uVbPxPkg8zg3KKWm3Y1ncw2kRDM2eb3CxtcCdSHIxvXXndia6o15H3F7coJ7ZTmAgEGMj6d2AmiCPUo/ruLo4qelYkXskQw2r+coATcFqcgffbnVq3iyu6JayFEIZ+BW2fTNAh8O+Iin7tP46f39+Omv2sKOsQ2+CYjnY08NWPVbOIO1NwdSirP5AMowFyZuwbYuMti9xEBEvctHuQx0lY29Bi0jXlNU15paJgKJB33KtI1XnfryBxSKRsYXQiK7H4OeeaKv5jw6YN54jL4jhSn89OBehU5KmLUbjh+JGeNOFmJYWAJDjPlPGYhfbx4mTOwlyKmRRfHkeR2CsQPUbhW3akoNzFgMOdUZlL/c2lJwjYIwS712jU+XUF56e8hA5/XSA8+Oa1J43fxGm/aGNtflzJyTLl9QRxqJbIq0VD3lxK4fpo0QnAtfxt3yLpTJ+7FvROWdCIzb4lMe5p1PbCP3J9tW9vnoFXPG+3FKY1Mw4kyj2ElOhOxa0d6U6KPU6zeoPrSjt5R6ixDbx+U/AsPZSZOGW5UPWYIAOiaZLJW9XqRnUZ9/kPVzAT4dnBdq+SaHpYljtnu9nR3cS83q6kN6Uw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: service-service-client-credential-flow-secret
      namespace: backend
    type: Opaque

